### ISSUE TITLE
Issues experienced during project setup 

### ISSUE THREAD

**Issue by lulufamilyOnTheSea** [paulxi/LeetCodeJava#1]
1. Use IntelliJ as IDE -> finally figured out that I need to use 'Inport' instead of 'Open' to inport the LeetCodeJava project.
2. Remove proxys from gradle.properties & .bash_profile
3. Inport jUnit 5.4 libraries
And can run unit test now yeah 👍

**Comment by paulxi** [comment]
You can use intellij Import Project, and then choose Gradle to let intellij automatically setup the project for you.
